version: "3.8"

# services
services:
  api-gateway:
    image: api-gateway:1.0.0
    container_name: api-gateway
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    networks:
      - sav-network

# networks
networks:
  sav-network:
    name: sav-network
