version: "3.8"
name: sav
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "127.1.1.0:9000:9000"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    networks:
      - sav-network
networks:
  sav-network:
    name: sav-network
    driver: bridge
