version: "3.8"
# services
services:
  microservice1:
    image: microservice1:1.0.0
    container_name: microservice1
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "9001:9000"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    networks:
      - sav-network

# networks
networks:
  sav-network:
    name: sav-network
