version: "3.8"
name: sav
services:
  mongodb:
    container_name: mongodb
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "127.1.1.1:27017:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - sav-network
volumes:
  data:
networks:
  sav-network:
    name: sav-network
