version: "3.8"
name: sav-backend
services:
  mongodb:
    container_name: mongodb
    build: .
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  data:
