version: "3.8"
name: sav
services:
  microservice3:
    container_name: microservice3
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "127.1.1.1:9003:9003"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    networks:
      - sav-network
networks:
  sav-network:
    name: sav-network
    driver: bridge
